## Name: Nagpurkar Manthan Tulsiram
## Enrollment No: 190130107071
## Subject: PDS(3150713)
## Sem: 5
## Class: CE-A

#                            Practical- 12

In [1]:
import pandas as pd
df = pd.read_csv('country_vaccinations.csv')

In [2]:
df.head(5)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,22-02-2021,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
1,Afghanistan,AFG,23-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
2,Afghanistan,AFG,24-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
3,Afghanistan,AFG,25-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
4,Afghanistan,AFG,26-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...

In [3]:
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,22-02-2021,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
1,Afghanistan,AFG,23-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
2,Afghanistan,AFG,24-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
3,Afghanistan,AFG,25-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
4,Afghanistan,AFG,26-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7612,Zimbabwe,ZWE,17-03-2021,39607.0,39607.0,NaN,57.0,529.0,0.27,0.27,NaN,36.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7613,Zimbabwe,ZWE,18-03-2021,40002.0,40002.0,NaN,395.0,569.0,0.27,0.27,NaN,38.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7614,Zimbabwe,ZWE,19-03-2021,41687.0,41687.0,NaN,1685.0,772.0,0.28,0.28,NaN,52.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7615,Zimbabwe,ZWE,20-03-2021,42210.0,42210.0,NaN,523.0,836.0,0.28,0.28,NaN,56.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7616,Zimbabwe,ZWE,21-03-2021,42729.0,42729.0,NaN,519.0,910.0,0.29,0.29,NaN,61.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...

In [4]:
df.info

<bound method DataFrame.info of           country iso_code        date  total_vaccinations  people_vaccinated  \
0     Afghanistan      AFG  22-02-2021                 0.0                0.0
1     Afghanistan      AFG  23-02-2021                 NaN                NaN
2     Afghanistan      AFG  24-02-2021                 NaN                NaN
3     Afghanistan      AFG  25-02-2021                 NaN                NaN
4     Afghanistan      AFG  26-02-2021                 NaN                NaN
...           ...      ...         ...                 ...                ...
7612     Zimbabwe      ZWE  17-03-2021             39607.0            39607.0
7613     Zimbabwe      ZWE  18-03-2021             40002.0            40002.0
7614     Zimbabwe      ZWE  19-03-2021             41687.0            41687.0
7615     Zimbabwe      ZWE  20-03-2021             42210.0            42210.0
7616     Zimbabwe      ZWE  21-03-2021             42729.0            42729.0

      people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations  \
0                         NaN                     NaN                 NaN
1                         NaN                     NaN              1367.0
2                         NaN                     NaN              1367.0
3                         NaN                     NaN              1367.0
4                         NaN                     NaN              1367.0
...                       ...                     ...                 ...
7612                      NaN                    57.0               529.0
7613                      NaN                   395.0               569.0
7614                      NaN                  1685.0               772.0
7615                      NaN                   523.0               836.0
7616                      NaN                   519.0               910.0

      total_vaccinations_per_hundred  people_vaccinated_per_hundred  \
0                               0.00                           0.00
1                                NaN                            NaN
2                                NaN                            NaN
3                                NaN                            NaN
4                                NaN                            NaN
...                              ...                            ...
7612                            0.27                           0.27
7613                            0.27                           0.27
7614                            0.28                           0.28
7615                            0.28                           0.28
7616                            0.29                           0.29

      people_fully_vaccinated_per_hundred  daily_vaccinations_per_million  \
0                                     NaN                             NaN
1                                     NaN                            35.0
2                                     NaN                            35.0
3                                     NaN                            35.0
4                                     NaN                            35.0
...                                   ...                             ...
7612                                  NaN                            36.0
7613                                  NaN                            38.0
7614                                  NaN                            52.0
7615                                  NaN                            56.0
7616                                  NaN                            61.0

                vaccines                source_name  \
0     Oxford/AstraZeneca  Government of Afghanistan
1     Oxford/AstraZeneca  Government of Afghanistan
2     Oxford/AstraZeneca  Government of Afghanistan
3     Oxford/AstraZeneca  Government of Afghanistan
4     Oxford/AstraZeneca  Government of Afghanistan
...                  ...                        ...
7612   Sinopharm/Beijing         Ministry of Health
7613   Sinopharm/Beijing         Ministry of Health
7614   Sinopharm/Beijing         Ministry of Health
7615   Sinopharm/Beijing         Ministry of Health
7616   Sinopharm/Beijing         Ministry of Health

                                         source_website
0     http://www.xinhuanet.com/english/asiapacific/2...
1     http://www.xinhuanet.com/english/asiapacific/2...
2     http://www.xinhuanet.com/english/asiapacific/2...
3     http://www.xinhuanet.com/english/asiapacific/2...
4     http://www.xinhuanet.com/english/asiapacific/2...
...                                                 ...
7612  https://twitter.com/MoHCCZim/status/1373715027...
7613  https://twitter.com/MoHCCZim/status/1373715027...
7614  https://twitter.com/MoHCCZim/status/1373715027...
7615  https://twitter.com/MoHCCZim/status/1373715027...
7616  https://twitter.com/MoHCCZim/status/1373715027...

[7617 rows x 15 columns]>

In [5]:
df.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,4.705000e+03,4.192000e+03,2.839000e+03,3.961000e+03,7.430000e+03,4705.000000,4192.000000,2839.000000,7430.000000
mean,2.455033e+06,1.979287e+06,8.396236e+05,8.880542e+04,5.971636e+04,9.632512,7.394280,3.474195,2678.791655
std,8.804826e+06,6.479318e+06,3.387952e+06,2.772719e+05,2.056971e+05,17.342720,11.793498,7.500373,4202.469571
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,3.805600e+04,3.529225e+04,1.826200e+04,2.708000e+03,1.011250e+03,0.740000,0.740000,0.380000,358.000000
50%,2.601940e+05,2.382790e+05,1.037860e+05,1.352000e+04,5.952500e+03,3.590000,3.100000,1.400000,1265.000000
75%,1.252461e+06,9.716248e+05,4.729120e+05,5.657200e+04,2.752900e+04,10.350000,8.132500,3.085000,3092.750000
max,1.244814e+08,8.141577e+07,4.414123e+07,4.575496e+06,2.541597e+06,157.820000,89.400000,68.420000,54264.000000

## Practical- 13

In [6]:
source_websites = df['source_website']
source_websites

0       http://www.xinhuanet.com/english/asiapacific/2...
1       http://www.xinhuanet.com/english/asiapacific/2...
2       http://www.xinhuanet.com/english/asiapacific/2...
3       http://www.xinhuanet.com/english/asiapacific/2...
4       http://www.xinhuanet.com/english/asiapacific/2...
                              ...
7612    https://twitter.com/MoHCCZim/status/1373715027...
7613    https://twitter.com/MoHCCZim/status/1373715027...
7614    https://twitter.com/MoHCCZim/status/1373715027...
7615    https://twitter.com/MoHCCZim/status/1373715027...
7616    https://twitter.com/MoHCCZim/status/1373715027...
Name: source_website, Length: 7617, dtype: object

In [7]:
special = df[['country', 'iso_code']]
special

          country iso_code
0     Afghanistan      AFG
1     Afghanistan      AFG
2     Afghanistan      AFG
3     Afghanistan      AFG
4     Afghanistan      AFG
...           ...      ...
7612     Zimbabwe      ZWE
7613     Zimbabwe      ZWE
7614     Zimbabwe      ZWE
7615     Zimbabwe      ZWE
7616     Zimbabwe      ZWE

[7617 rows x 2 columns]

In [8]:
special = df[['iso_code', 'country']]
special

     iso_code      country
0         AFG  Afghanistan
1         AFG  Afghanistan
2         AFG  Afghanistan
3         AFG  Afghanistan
4         AFG  Afghanistan
...       ...          ...
7612      ZWE     Zimbabwe
7613      ZWE     Zimbabwe
7614      ZWE     Zimbabwe
7615      ZWE     Zimbabwe
7616      ZWE     Zimbabwe

[7617 rows x 2 columns]

In [9]:
dfiloc = df.iloc[:3, :5]
dfiloc

       country iso_code        date  total_vaccinations  people_vaccinated
0  Afghanistan      AFG  22-02-2021                 0.0                0.0
1  Afghanistan      AFG  23-02-2021                 NaN                NaN
2  Afghanistan      AFG  24-02-2021                 NaN                NaN

In [10]:
dfiloc = df.iloc[0:10,:-1]
dfiloc

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name
0,Afghanistan,AFG,22-02-2021,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan
1,Afghanistan,AFG,23-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan
2,Afghanistan,AFG,24-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan
3,Afghanistan,AFG,25-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan
4,Afghanistan,AFG,26-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan
5,Afghanistan,AFG,27-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan
6,Afghanistan,AFG,28-02-2021,8200.0,8200.0,NaN,NaN,1367.0,0.02,0.02,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan
7,Afghanistan,AFG,01-03-2021,NaN,NaN,NaN,NaN,1580.0,NaN,NaN,NaN,41.0,Oxford/AstraZeneca,Government of Afghanistan
8,Afghanistan,AFG,02-03-2021,NaN,NaN,NaN,NaN,1794.0,NaN,NaN,NaN,46.0,Oxford/AstraZeneca,Government of Afghanistan
9,Afghanistan,AFG,03-03-2021,NaN,NaN,NaN,NaN,2008.0,NaN,NaN,NaN,52.0,Oxford/AstraZeneca,Government of Afghanistan

In [11]:
dfiloc = df.iloc[1, 2] ## df.iloc[row, col]
dfiloc

'23-02-2021'

In [12]:
dfloc = df.loc[[0,5], ['country', 'iso_code']]
dfloc

       country iso_code
0  Afghanistan      AFG
5  Afghanistan      AFG

In [13]:
dfloc = df.loc[[1,10,3553], :]
dfloc

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
1,Afghanistan,AFG,23-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
10,Afghanistan,AFG,04-03-2021,NaN,NaN,NaN,NaN,2221.0,NaN,NaN,NaN,57.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
3553,Israel,ISR,26-01-2021,4225642.0,2798842.0,1426800.0,204420.0,184055.0,48.82,32.34,16.48,21264.0,"Moderna, Pfizer/BioNTech",Government of Israel,https://datadashboard.health.gov.il/COVID-19/g...

In [14]:
df[df.country=='India']

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
3205,India,IND,15-01-2021,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3206,India,IND,16-01-2021,191181.0,191181.0,NaN,191181.0,191181.0,0.01,0.01,NaN,139.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3207,India,IND,17-01-2021,224301.0,224301.0,NaN,33120.0,112150.0,0.02,0.02,NaN,81.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3208,India,IND,18-01-2021,454049.0,454049.0,NaN,229748.0,151350.0,0.03,0.03,NaN,110.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3209,India,IND,19-01-2021,674835.0,674835.0,NaN,220786.0,168709.0,0.05,0.05,NaN,122.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,India,IND,17-03-2021,37143255.0,30600787.0,6542468.0,2078719.0,1636892.0,2.69,2.22,0.47,1186.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3267,India,IND,18-03-2021,39339817.0,32426230.0,6913587.0,2196562.0,1882128.0,2.85,2.35,0.50,1364.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3268,India,IND,19-03-2021,42063392.0,34842030.0,7221362.0,2723575.0,1977848.0,3.05,2.52,0.52,1433.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3269,India,IND,20-03-2021,44603841.0,37125187.0,7478654.0,2540449.0,2123633.0,3.23,2.69,0.54,1539.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...
3270,India,IND,21-03-2021,45065998.0,37574302.0,7491696.0,462157.0,2165423.0,3.27,2.72,0.54,1569.0,"Covaxin, Oxford/AstraZeneca",Ministry of Health,http://mohfw.gov.in/pdf/CumulativeCOVIDVaccina...

In [15]:
df[:5]

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,22-02-2021,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
1,Afghanistan,AFG,23-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
2,Afghanistan,AFG,24-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
3,Afghanistan,AFG,25-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
4,Afghanistan,AFG,26-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...

In [16]:
df[:-1]

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,22-02-2021,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
1,Afghanistan,AFG,23-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
2,Afghanistan,AFG,24-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
3,Afghanistan,AFG,25-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
4,Afghanistan,AFG,26-02-2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,http://www.xinhuanet.com/english/asiapacific/2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7611,Zimbabwe,ZWE,16-03-2021,39550.0,39550.0,NaN,1890.0,541.0,0.27,0.27,NaN,36.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7612,Zimbabwe,ZWE,17-03-2021,39607.0,39607.0,NaN,57.0,529.0,0.27,0.27,NaN,36.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7613,Zimbabwe,ZWE,18-03-2021,40002.0,40002.0,NaN,395.0,569.0,0.27,0.27,NaN,38.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7614,Zimbabwe,ZWE,19-03-2021,41687.0,41687.0,NaN,1685.0,772.0,0.28,0.28,NaN,52.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...
7615,Zimbabwe,ZWE,20-03-2021,42210.0,42210.0,NaN,523.0,836.0,0.28,0.28,NaN,56.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1373715027...

## Practical-14

In [17]:
df.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,4.705000e+03,4.192000e+03,2.839000e+03,3.961000e+03,7.430000e+03,4705.000000,4192.000000,2839.000000,7430.000000
mean,2.455033e+06,1.979287e+06,8.396236e+05,8.880542e+04,5.971636e+04,9.632512,7.394280,3.474195,2678.791655
std,8.804826e+06,6.479318e+06,3.387952e+06,2.772719e+05,2.056971e+05,17.342720,11.793498,7.500373,4202.469571
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,3.805600e+04,3.529225e+04,1.826200e+04,2.708000e+03,1.011250e+03,0.740000,0.740000,0.380000,358.000000
50%,2.601940e+05,2.382790e+05,1.037860e+05,1.352000e+04,5.952500e+03,3.590000,3.100000,1.400000,1265.000000
75%,1.252461e+06,9.716248e+05,4.729120e+05,5.657200e+04,2.752900e+04,10.350000,8.132500,3.085000,3092.750000
max,1.244814e+08,8.141577e+07,4.414123e+07,4.575496e+06,2.541597e+06,157.820000,89.400000,68.420000,54264.000000

In [18]:
max(df.total_vaccinations)

124481412.0

In [19]:
max(df.total_vaccinations_per_hundred)

157.82

In [20]:
min(df.total_vaccinations_per_hundred)

0.0

In [21]:
pd.DataFrame.mean(df.total_vaccinations)

2455032.724335813

In [22]:
pd.DataFrame.mean(df.daily_vaccinations)

59716.35585464334

In [23]:
pd.DataFrame.median(df.total_vaccinations)

260194.0

In [24]:
pd.DataFrame.median(df.daily_vaccinations)

5952.5

In [25]:
df.count()

country                                7617
iso_code                               7617
date                                   7617
total_vaccinations                     4705
people_vaccinated                      4192
people_fully_vaccinated                2839
daily_vaccinations_raw                 3961
daily_vaccinations                     7430
total_vaccinations_per_hundred         4705
people_vaccinated_per_hundred          4192
people_fully_vaccinated_per_hundred    2839
daily_vaccinations_per_million         7430
vaccines                               7617
source_name                            7617
source_website                         7617
dtype: int64

In [26]:
df.median()

<ipython-input-26-6d467abf240d>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()

total_vaccinations                     260194.00
people_vaccinated                      238279.00
people_fully_vaccinated                103786.00
daily_vaccinations_raw                  13520.00
daily_vaccinations                       5952.50
total_vaccinations_per_hundred              3.59
people_vaccinated_per_hundred               3.10
people_fully_vaccinated_per_hundred         1.40
daily_vaccinations_per_million           1265.00
dtype: float64

In [27]:
df.mean()

<ipython-input-27-c61f0c8f89b5>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()

total_vaccinations                     2.455033e+06
people_vaccinated                      1.979287e+06
people_fully_vaccinated                8.396236e+05
daily_vaccinations_raw                 8.880542e+04
daily_vaccinations                     5.971636e+04
total_vaccinations_per_hundred         9.632512e+00
people_vaccinated_per_hundred          7.394280e+00
people_fully_vaccinated_per_hundred    3.474195e+00
daily_vaccinations_per_million         2.678792e+03
dtype: float64

In [28]:
df.std()

<ipython-input-28-ce97bb7eaef8>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()

total_vaccinations                     8.804826e+06
people_vaccinated                      6.479318e+06
people_fully_vaccinated                3.387952e+06
daily_vaccinations_raw                 2.772719e+05
daily_vaccinations                     2.056971e+05
total_vaccinations_per_hundred         1.734272e+01
people_vaccinated_per_hundred          1.179350e+01
people_fully_vaccinated_per_hundred    7.500373e+00
daily_vaccinations_per_million         4.202470e+03
dtype: float64

In [29]:
pd.DataFrame.std(df.total_vaccinations)

8804825.909219619

In [30]:
df.corr()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
total_vaccinations,1.000000,0.990072,0.946449,0.886508,0.941822,0.176660,0.187972,0.086810,0.115724
people_vaccinated,0.990072,1.000000,0.891601,0.893285,0.950872,0.174673,0.201670,0.057612,0.119541
people_fully_vaccinated,0.946449,0.891601,1.000000,0.810943,0.865925,0.128914,0.109543,0.147242,0.097943
daily_vaccinations_raw,0.886508,0.893285,0.810943,1.000000,0.940825,0.090077,0.102503,0.023373,0.090440
daily_vaccinations,0.941822,0.950872,0.865925,0.940825,1.000000,0.094536,0.107640,0.027706,0.049583
total_vaccinations_per_hundred,0.176660,0.174673,0.128914,0.090077,0.094536,1.000000,0.976098,0.926070,0.778634
people_vaccinated_per_hundred,0.187972,0.201670,0.109543,0.102503,0.107640,0.976098,1.000000,0.823180,0.816010
people_fully_vaccinated_per_hundred,0.086810,0.057612,0.147242,0.023373,0.027706,0.926070,0.823180,1.000000,0.726833
daily_vaccinations_per_million,0.115724,0.119541,0.097943,0.090440,0.049583,0.778634,0.816010,0.726833,1.000000

## Practical-15

In [35]:
df.groupby(['total_vaccinations', 'people_vaccinated']).mean()

,,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
total_vaccinations,people_vaccinated,,,,,,,
3049.0,2438.0,611.0,1348.0,254.0,0.11,0.08,0.02,88.0
4886.0,4247.0,639.0,677.0,266.0,5.75,4.99,0.75,3128.0
5587.0,4550.0,1037.0,701.0,338.0,6.57,5.35,1.22,3975.0
6281.0,5243.0,1038.0,694.0,389.0,7.39,6.17,1.22,4575.0
6524.0,6524.0,6524.0,4264.0,2175.0,0.01,0.01,0.01,37.0
...,...,...,...,...,...,...,...,...
113037627.0,73669956.0,39989196.0,2299771.0,2473762.0,33.80,22.03,11.96,7397.0
115730008.0,75495716.0,40981464.0,2692381.0,2503731.0,34.60,22.57,12.25,7486.0
118313818.0,77230061.0,41934629.0,2583810.0,2455116.0,35.38,23.09,12.54,7341.0
121441497.0,79367225.0,43036818.0,3127679.0,2248285.0,36.31,23.73,12.87,6723.0
124481412.0,81415769.0,44141228.0,3039915.0,2488734.0,37.22,24.34,13.20,7441.0

In [39]:
first_5 = df.head(5)
last_5 = df[2555:]
combo = pd.concat([first_5, last_5], axis=0)
combo

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
62,Albania,ALB,18-02-2021,3049.0,2438.0,611.0,1348.0,254.0,0.11,0.08,0.02,88.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
270,Argentina,ARG,21-01-2021,265724.0,249372.0,16352.0,17791.0,11704.0,0.59,0.55,0.04,259.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V",Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
271,Argentina,ARG,22-01-2021,279602.0,254456.0,25146.0,13878.0,11263.0,0.62,0.56,0.06,249.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V",Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
272,Argentina,ARG,23-01-2021,288064.0,258876.0,29188.0,8462.0,11124.0,0.64,0.57,0.06,246.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V",Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
273,Argentina,ARG,24-01-2021,292023.0,260036.0,31987.0,3959.0,10342.0,0.65,0.58,0.07,229.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V",Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
7580,Wales,OWID_WLS,16-03-2021,1446436.0,1157251.0,289185.0,33587.0,31547.0,45.88,36.70,9.17,10006.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
7581,Wales,OWID_WLS,17-03-2021,1484566.0,1180155.0,304411.0,38130.0,32646.0,47.09,37.43,9.66,10354.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
7582,Wales,OWID_WLS,18-03-2021,1523077.0,1204101.0,318976.0,38511.0,32705.0,48.31,38.19,10.12,10373.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
7583,Wales,OWID_WLS,19-03-2021,1561360.0,1231830.0,329530.0,38283.0,32429.0,49.52,39.07,10.45,10286.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
7584,Wales,OWID_WLS,20-03-2021,1597728.0,1258769.0,338959.0,36368.0,32405.0,50.68,39.92,10.75,10278.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...

In [42]:
df1= [['Jigar', 'Makwana', 'DAIICT'], ['Manthan', 'Nagpurkar', 'GEC'], ['Sanidhya', 'Dhabi', 'LD']] 
df2 = pd.DataFrame(df1, columns = ['Name', 'Surname', 'College'])
df2

       Name    Surname College
0     Jigar    Makwana  DAIICT
1   Manthan  Nagpurkar     GEC
2  Sanidhya      Dhabi      LD

In [44]:
df1 = ['Gandhinagar', 'Gandhinagar', 'Ahmedabad']
df3 = pd.DataFrame(df1, columns=['District'])
df3

      District
0  Gandhinagar
1  Gandhinagar
2    Ahmedabad

In [54]:
f_df = pd.merge(df3, df2, how='right', on='District')
f_df

      District
0  Gandhinagar
1  Gandhinagar
2  Gandhinagar
3  Gandhinagar
4    Ahmedabad

## Practical-16

In [31]:
df.isnull().sum()

country                                   0
iso_code                                  0
date                                      0
total_vaccinations                     2912
people_vaccinated                      3425
people_fully_vaccinated                4778
daily_vaccinations_raw                 3656
daily_vaccinations                      187
total_vaccinations_per_hundred         2912
people_vaccinated_per_hundred          3425
people_fully_vaccinated_per_hundred    4778
daily_vaccinations_per_million          187
vaccines                                  0
source_name                               0
source_website                            0
dtype: int64

In [32]:
df.empty

False

In [33]:
x = pd.to_datetime('date', errors='coerce')
x

NaT

## Practical-17

In [34]:
def total_vaccinations_world(vac):
    sum = 0.0   
    l = lambda x: x
    for value in vac:
        sum = sum+l(value)
    return sum

df = df.dropna()
ans = total_vaccinations_world(df.total_vaccinations)
print(f'total vaccinated people all over the world = {ans}')

total vaccinated people all over the world = 10039261232.0